name: SimpleMail
description: A simple mail plugin for Bukkit servers
version: 2.0

author: x3chaos
website: http://github.com/x3chaos/simplemail

main: org.x3.mail.SimpleMail
database: false

commands:
  mail:
    description: SimpleMail catch-all command
    aliases: [sm]
    usage: |
      Incorrect usage.
      SimpleMail help: /<command> help [topic]

permissions:
  simplemail.send.*:
    description: Allows a user to send any message to anyone
    default: op
    children:
      simplemail.send.admin: true
      simplemail.send.player: true
  simplemail.send.admin:
    description: Allows a player to send a message to a protected admin
    default: false
  simplemail.send.player:
    description: Allows a player to send a message to a non-admin player
    default: true